# -*- coding: utf-8 -*-
"""XGboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppvXI_Xh8kqcmp0xbqyPmsEZU4ba7fdi
"""

# =========================
# STEP 1: Import Libraries
# =========================
import pandas as pd
import numpy as np # <-- FIXED BUG HERE
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    ConfusionMatrixDisplay,
    roc_auc_score,
    roc_curve,
    auc
)

# NOTE: You may need to run `pip install xgboost` in your terminal
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings("ignore")

RANDOM_STATE = 42

# =========================
# STEP 2: Load Dataset
# =========================
df = pd.read_csv("Processed_ObesityDataSet.csv")

# =========================
# STEP 3: Target Encoding & Feature Selection
# =========================
X = df.drop(["NObeyesdad"], axis=1, errors='ignore')

# XGBoost strictly requires targets to be integers starting from 0
y = df['NObeyesdad'].astype(int)

class_labels = [
    "Insufficient Weight", "Normal Weight", "Overweight Level I",
    "Overweight Level II", "Obesity Type I", "Obesity Type II", "Obesity Type III"
]

# One-Hot Encoding
X = pd.get_dummies(X, drop_first=True)

# Clean up ALL column names for professional graphs
rename_dict = {
    'FCVC': 'Vegetable Consumption', 'NCP': 'Number of Main Meals',
    'CAEC': 'Eats Between Meals', 'CH2O': 'Water Consumption',
    'FAF': 'Physical Activity', 'TUE': 'Time on Devices',
    'CALC': 'Alcohol Consumption', 'Gender_Male': 'Gender',
    'family_history_with_overweight_yes': 'Family History of Overweight',
    'FAVC_yes': 'Eats High Caloric Food', 'SMOKE_yes': 'Smoker',
    'SCC_yes': 'Monitors Calories', 'MTRANS_Bike': 'Transport: Bike',
    'MTRANS_Motorbike': 'Transport: Motorbike',
    'MTRANS_Public_Transportation': 'Transport: Public Transit',
    'MTRANS_Walking': 'Transport: Walking'
}
X = X.rename(columns=rename_dict)

# =========================
# STEP 4: Train-Test Split (80/20)
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

# =========================
# STEP 5 & 6: Pipeline & Advanced Regularized GridSearch
# =========================
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('xgb', XGBClassifier(objective='multi:softprob', eval_metric='mlogloss', random_state=RANDOM_STATE))
])

# UPGRADED PARAMETER GRID: Focused entirely on closing the Train-Test Gap
param_grid = {
    'xgb__n_estimators': [100, 125],
    'xgb__learning_rate': [0.03, 0.05],
    'xgb__max_depth': [2, 3],
    'xgb__min_child_weight': [5, 7],
    'xgb__gamma': [1.0, 2.0],
    'xgb__subsample': [0.7],
    'xgb__colsample_bytree': [0.7],
    'xgb__reg_alpha': [0.5, 1.0],
    'xgb__reg_lambda': [1.0, 5.0]
}

print("Starting Highly Regularized Grid Search for XGBoost... (Closing the gap)")
grid = GridSearchCV(pipe, param_grid, cv=5, n_jobs=-1, verbose=1)
grid.fit(X_train, y_train)

best_model = grid.best_estimator_

# =========================
# STEP 7: Performance Evaluation
# =========================
y_train_pred = best_model.predict(X_train)
y_test_pred = best_model.predict(X_test)

print("\n--- XGBOOST RESULTS ---")
print(f"Best Parameters: {grid.best_params_}")
print(f"Cross-Validation Accuracy: {grid.best_score_:.4f}")
print(f"Train Accuracy: {accuracy_score(y_train, y_train_pred):.4f}")
print(f"Test Accuracy: {accuracy_score(y_test, y_test_pred):.4f}")
# MOVED HERE FOR CONSISTENCY
print(f"Generalization Gap: {abs(accuracy_score(y_train, y_train_pred) - accuracy_score(y_test, y_test_pred)):.2%}")

# =========================
# STEP 8: Classification Report
# =========================
report_dict = classification_report(
    y_test, y_test_pred, target_names=class_labels, output_dict=True
)

report_df = pd.DataFrame(report_dict).transpose()
report_df.index = list(report_df.index[:-3]) + ['Overall Accuracy', 'Macro Avg', 'Weighted Avg']
report_df = report_df.round(2)

print("\n--- FINAL CLASSIFICATION REPORT ---")
print(report_df)

# =========================
# STEP 9: Visualizations
# =========================
# Confusion Matrix
fig, ax = plt.subplots(figsize=(10, 8))
ConfusionMatrixDisplay.from_estimator(
    best_model, X_test, y_test,
    display_labels=class_labels, cmap="Reds", ax=ax, xticks_rotation=45
)
plt.title("Confusion Matrix: XGBoost")
plt.tight_layout()
plt.savefig("confusion_matrix_xgboost.png")
plt.show()

# =========================
# STEP 10: Final Metrics (ROC & AUC)
# =========================
y_prob = best_model.predict_proba(X_test)
y_test_bin = label_binarize(y_test, classes=best_model.classes_)
auc_score = roc_auc_score(y_test_bin, y_prob, multi_class='ovr')

print(f"\nFinal AUC Score (Multiclass): {auc_score:.4f}")

n_classes = len(best_model.classes_)

plt.figure(figsize=(10, 8))
colors = sns.color_palette("husl", n_classes)

for i, color in zip(range(n_classes), colors):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, color=color, lw=2, label=f'{class_labels[i]} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Multiclass ROC Curve (XGBoost)')
plt.legend(loc="lower right")
plt.tight_layout()
plt.savefig("roc_curve_xgboost.png")
plt.show()

# =========================
# Step 11: Feature Importance (Native XGBoost)
# =========================
# MOVED HERE FOR CONSISTENCY
xgb_model = best_model.named_steps['xgb']
feature_names = X.columns
importances = xgb_model.feature_importances_
indices = np.argsort(importances)

plt.figure(figsize=(10, 8))
plt.title("XGBoost Feature Importance (Native)")
plt.barh(range(len(indices)), importances[indices], color='crimson', align='center')
plt.yticks(range(len(indices)), [feature_names[i] for i in indices])
plt.xlabel("Relative Importance Score")
plt.tight_layout()
plt.savefig("xgboost_feature_importance.png")
plt.show()

# =========================
# Step 12: Learning Curve (Proving the Gap is Closed)
# =========================
# MOVED HERE FOR CONSISTENCY
print("\nGenerating Learning Curve to visualize the Generalization Gap...")

train_sizes, train_scores, lc_test_scores = learning_curve(
    best_model, X_train, y_train, cv=5, n_jobs=-1,
    train_sizes=np.linspace(0.2, 1.0, 5), scoring='accuracy'
)

train_mean = np.mean(train_scores, axis=1)
train_std = np.std(train_scores, axis=1)
test_mean = np.mean(lc_test_scores, axis=1)
test_std = np.std(lc_test_scores, axis=1)

plt.figure(figsize=(8, 6)) # Updated to match 8,6 from other scripts
plt.plot(train_sizes, train_mean, 'o-', color="r", label="Training score")
plt.fill_between(train_sizes, train_mean - train_std, train_mean + train_std, alpha=0.1, color="r")
plt.plot(train_sizes, test_mean, 'o-', color="g", label="Cross-validation score")
plt.fill_between(train_sizes, test_mean - test_std, test_mean + test_std, alpha=0.1, color="g")

plt.title("Learning Curve (XGBoost)")
plt.xlabel("Number of Training Examples")
plt.ylabel("Accuracy Score")
plt.legend(loc="best")
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig("xgboost_learning_curve.png")
plt.show()

# --- ADD THIS TO THE VERY BOTTOM ---
import joblib
import json

print("\nExporting model and metadata for Streamlit...")

# Save the Pipeline (Scaler + XGBoost)
joblib.dump(best_model, "xgboost_model.joblib")

# Save the exact feature columns and labels
metadata = {
    "feature_columns": list(X.columns),
    "class_labels": class_labels
}

with open("xgboost_metadata.json", "w") as f:
    json.dump(metadata, f)

print("Export complete! 'xgboost_model.joblib' and 'xgboost_metadata.json' are ready.")